### ISSUE TITLE
recitationの55番と283番の文ついて、pdfとtxtで相違があります

### ISSUE THREAD

**Issue by Haruqa** [mmorise/ita-corpus#1]
こんにちは、素晴らしいコーパスの公開ありがとうございます。
2点、pdfとtxtファイルで相違がある文を見つけましたので、報告させていただきます。

■1点目
recitationの55番
「、」がある/ないで相違があります。

pdf：ヌルシアのベネディクトゥスはアポロン神殿を壊し、ベネディクト会の修道院を建てた。
txt：ヌルシアのベネディクトゥスはアポロン神殿を壊しベネディクト会の修道院を建てた。
https://github.com/mmorise/ita-corpus/blob/main/recitation_transcript_utf8.txt#L55

■2点目
recitationの283番
「併せて」「合わせて」で相違があります。

pdf：インスティテュートで、リデュースの話と併せて、ルデュックの話も聞いた。
txt：インスティテュートで、リデュースの話と合わせて、ルデュックの話も聞いた。
https://github.com/mmorise/ita-corpus/blob/main/recitation_transcript_utf8.txt#L283

以上です。よろしくお願いいたします。

**Comment by mmorise** [comment]
ご指摘ありがとうございます．
担当者に確認したところ，どちらもpdfが正しいとのことでした．テキストの方を修正するようにします．

**Comment by Haruqa** [comment]
修正を確認しました。ご対応ありがとうございます！
