### ISSUE TITLE
Trailing `。` mismatch in 2 examples

### ISSUE THREAD

**Issue by glebm** [mmorise/ita-corpus#2]
In these examples, the pronunciation contains a trailing `。` but the text does not:

```
RECITATION324_089:仏教はインド由来の宗教です,ブッキョーワインドユライノシュウキョーデス。
RECITATION324_140:ハサミでプツッと切った切れ端をペットにあげた,ハサミデプツットキッタキレハシヲペットニアゲタ。
```

**Comment by mmorise** [comment]
Thank you very much for your suggestion.
We revised the sentences according to your comment.

**Comment by glebm** [comment]
Thanks!
