### ISSUE TITLE
疑問符の表記について

### ISSUE THREAD

**Issue by fuso-adashino** [mmorise/ita-corpus#3]
こんにちは。
.txtファイル内のカナ表記部分に関して、EMOTIONとRECITATIONで疑問符の扱いが違うのは仕様でしょうか。

**状況**
```
EMOTION100_XXX:～～～ですか？,～～～デスカ。
RECITATION324_XXX:～～～ですか？,～～～デスカ？
```
**該当箇所**
EMOTION100　28番、40番、57番
RECITATION324　31番、60番、229番

もしかしたら余計なお世話かなとも思いましたが、念のため確認させていただきました。ご確認いただけますと幸いです。

**Comment by mmorise** [comment]
こちら，設定ミスなので修正するように致します．
申し訳ありませんが，火曜水曜の予定が完全に埋まっているので，対応は木曜以降とさせて頂ければ幸いです．

**Comment by fuso-adashino** [comment]
ありがとうございます。私は急ぎではないので大丈夫です。

**Comment by mmorise** [comment]
ご指摘ありがとうございました．どちらもRECITATIONと同じで漢字込みのテキストとカタカナ文の両方に疑問符をつけるように修正いたしました．

**Comment by fuso-adashino** [comment]
確認しました。ご対応、ありがとうございました。
