### ISSUE TITLE
テキストと読みの不一致

### ISSUE THREAD

**Issue by Hiroshiba** [mmorise/ita-corpus#4]
テキストと読みの不一致を見つけたので報告します。

テキスト：ギャロウェイさん
読み：ギャローェイサン

https://github.com/mmorise/ita-corpus/blob/2701c278e16084a953f3240b9cd122c0ebdd089d/recitation_transcript_utf8.txt#L142

**Comment by mmorise** [comment]
ありがとうございます．こちら，PRを反映いたしました．
