### ISSUE TITLE
朗読者向けファイルのEMOTION100_014で「私」にルビがない

### ISSUE THREAD

**Issue by so-c** [mmorise/ita-corpus#7]
emotion_朗読者用（docx, pdfともに）のEMOTION100_014「スミスさん、ピエール・デュボワをご紹介しますわ。私の親友なの。」の「私」にルビがありません。

emotion_transcript_ruby_utf8.txt で「わたし」だと確認できますが、収録時の利便性のために追加してもらえると嬉しいです

**Comment by mmorise** [comment]
ご指摘ありがとうございます．親友のルビ位置も変だったので，併せて修正いたしました．

**Comment by so-c** [comment]
早速のご対応ありがとうございました。読みやすくなりました。
