### ISSUE TITLE
PDF版のrecitation_朗読者用-13の「1877」にルビがほしい

### ISSUE THREAD

**Issue by Hiroshiba** [mmorise/ita-corpus#9]
PDF版のrecitation_朗読者用-13の「1877」にルビがあると便利に思いました。

txt版をみると「せんはっぴゃくななじゅうなな」だとわかるのですが、「いちはちななな」と迷うことがあったのでご報告です。

**Comment by mmorise** [comment]
コメントありがとうございます．
修正いたしました．

**Comment by Hiroshiba** [comment]
確認できました！　ありがとうございます！
